Hw 5
polisgo2020/search-Arkronzxc pull request #6
Opened 2020-04-13 15:38 UTC by Arkronzxc

Переборщил с логированием из-за чего сервер долго поднимается - исправлю чуть позже

2020-04-13 15:41 UTC, Arkronzxc commented
Переборщил с логированием из-за чего сервер долго поднимается - исправлю чуть позже

2020-04-14 19:25 UTC, tariel-x commented
А предыдущий PR почему не доделали до конца?

2020-04-15 19:42 UTC, tariel-x commented
Код не компилируется:
```
$ go build
import cycle not allowed
package github.com/polisgo2020/search-Arkronzxc
        imports github.com/polisgo2020/search-Arkronzxc/index
        imports github.com/polisgo2020/search-Arkronzxc/files
        imports github.com/polisgo2020/search-Arkronzxc/util
        imports github.com/polisgo2020/search-Arkronzxc/index
```

2020-04-16 06:47 UTC, Arkronzxc commented
Я сразу это исправил, но забыл запушить :(

2020-04-18 21:09 UTC, tariel-x requested changes
web.go можно переписать таким образом:

```golang
package web

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi"
	"github.com/polisgo2020/search-Arkronzxc/index"
	"github.com/rs/zerolog/log"
)

type searchResponse struct {
	Filename         string `json:"filename"`
	WordsEncountered int    `json:"wordsEncountered"`
}

type service struct {
	idx *index.Index
}

func (s *service) handlerSearch(writer http.ResponseWriter, request *http.Request) {
	query := request.FormValue("search")
	results, err := s.idx.Search(query)

	if err != nil {
		if errors.Is(err, index.BadQuery) {
			http.Error(writer, http.StatusText(http.StatusBadRequest), http.StatusBadRequest)
			return
		}
		log.Err(err).Msg("error searching")
		http.Error(writer, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}

	var resp []*searchResponse
	for i := range results {
		resp = append(resp, &searchResponse{
			Filename:         i,
			WordsEncountered: results[i],
		})
	}

	respJson, err := json.Marshal(resp)
	if err != nil {
		log.Err(err).Msg("error marshaling response")
		http.Error(writer, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}

	if _, err := fmt.Fprint(writer, string(respJson)); err != nil {
		log.Err(err).Msg("Error while ")
		http.Error(writer, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}
}

func logMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		next.ServeHTTP(w, r)
		log.Debug().
			Str("method", r.Method).
			Str("remote", r.RemoteAddr).
			Str("path", r.URL.Path).
			Int("duration", int(time.Since(start))).
			Msgf("Called url %s", r.URL.Path)
	})
}

func jsonMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		next.ServeHTTP(w, r)
	})
}

func Start(idx *index.Index, iface string) error {
	s := &service{
		idx: idx,
	}

	r := chi.NewRouter()
	r.Use(logMiddleware)

	r.Route("/api", func(r chi.Router) {
		r.Use(jsonMiddleware)
		r.Get("/", s.handlerSearch)
	})

	r.Get("/*", func(writer http.ResponseWriter, request *http.Request) {
		h := http.FileServer(http.Dir("./static"))
		h.ServeHTTP(writer, request)
	})

	log.Info().Msgf("started to listen at interface %s", iface)
	return http.ListenAndServe(iface, r)
}
```
остальной код допишите сами.

2020-04-18 21:09 UTC, tariel-x commented on config/config.go
> +	var listen, logLevel string
Кажется, что эти 2 переменные нигде не используются.

2020-04-18 21:09 UTC, tariel-x commented on main.go
> +		log.Err(err).Msg("Can't initialize console application")
В эту err по идее записываются ошибки, возникшие при работе приложения, поэтому такой текст ошибки может быть неуместным.

2020-04-18 21:09 UTC, tariel-x commented on main.go
> +		log.Err(err).Str("File names", ctx.String("sources")).Msg("Error while reading files")
Вообще, здесь и в других местах происходит дублирование логирования. Ошибка и так возвращается наверх, где логируется. Возможно, можно подумать о том, чтоб вместо дополнительного логирования делать так:
```golang
return fmt.Errorf("Some additional description: %w", err)
```
В этом месте `%w` означает заворачивание одной ошибки в другую и потом проверять с помощью https://golang.org/pkg/errors/#As.

2020-04-18 21:09 UTC, tariel-x commented on main.go
> +			log.Err(err).Interface("Inverted index", invertedIndex).Msg("Error while creating inverted index")
Вот эта строка может вывести в stdout очень много данных, которые засорят лог.

2020-04-18 21:09 UTC, tariel-x commented on main.go
> +	_ = web.StartingWeb(ctx.String("index"), ctx.String("port"))
Почему не вернуть ошибку через return?

2020-04-18 21:09 UTC, tariel-x commented on web/web.go
> +		log.Err(err).Msg("can't start server")
Здесь тоже стоит просто сделать return ошибки.

2020-04-18 21:09 UTC, tariel-x commented on index/index.go
>  	m := make(map[string]string)
В такой инициализации нет большого смысла: можно делать просто `map[string]string{}`.

2020-04-18 21:09 UTC, tariel-x commented on web/web.go
> +	cleanedUserInput := make([]string, 0)
В такой инициализации нет большого смысла, предпочтительней `var abc []string`: https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices .
А в данном случае имеет смысл оставить make, но передать третьим аргументом длину parsedUserInput.

2020-04-18 21:09 UTC, tariel-x commented on web/web.go
> +		log.Printf("filename: %s, words encountered : %d", s, ans[s])
Что здесь делает этот логгер?

2020-04-18 21:09 UTC, tariel-x commented on web/web.go
> +			log.Err(err).Msg("Error while ")
Error while what?

2020-04-18 21:09 UTC, tariel-x commented on web/web.go
> +		panic(err)
Почему это здесь?

2020-04-18 21:09 UTC, tariel-x commented on main.go
> +	_ = web.StartingWeb(ctx.String("index"), ctx.String("port"))
Ещё здесь нет проверки на то, что параметр port передан. Это можно сделать средствами библиотеки cli при инициализации флага.

2020-04-18 21:09 UTC, tariel-x commented on main.go
> +		DefaultText: "8888",
Лучше бы принимать не `port`, а интерфейс целиком, например `0.0.0.0:8888`, потому как можен быть необходимо, чтоб демон слушал только определённый интерфейс.

2020-04-18 21:09 UTC, tariel-x commented on main.go
> +	err = app.Run(os.Args)
Я запустил приложение `go run main.go build` и рассчитывал получить подсказу, что делать дальше, но получилось так:
```
$ go run main.go build
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7d18af]
```

2020-04-18 21:09 UTC, tariel-x commented on main.go
>  				searchFlag,
Этот флаг явно больше нигде не используется. Зачем он здесь?

2020-04-18 21:09 UTC, tariel-x commented on main.go
> +	if err = initLogger(config.Load()); err != nil {
Там внутри есть ещё и LISTEN, который не используется. Почему?

2020-04-21 14:52 UTC, Arkronzxc commented on config/config.go
> +	var listen, logLevel string
Done

2020-04-21 14:53 UTC, Arkronzxc commented on main.go
> +	err = app.Run(os.Args)
Done

2020-04-21 14:54 UTC, Arkronzxc commented on main.go
> +	if err = initLogger(config.Load()); err != nil {
Используется. Done

2020-04-23 22:08 UTC, tariel-x commented on config/config.go
> +	var listen, logLevel string
Кажется, что ничего не поменялось.

2020-04-23 22:10 UTC, tariel-x commented
Тут конфликты с master ещё.

2020-04-23 22:17 UTC, tariel-x commented on main.go
> +	err = web.StartingWeb(searchIndex, c)
Почему бы не сделать `return web.StartingWeb(searchIndex, c)`?

2020-04-23 22:17 UTC, tariel-x commented on main.go
> +			log.Err(err).Interface("Inverted index", invertedIndex).Msg("Error while creating inverted index")
Тут есть ещё и другие такие же ситуации, например: `log.Debug().Interface("Index", searchIndex)`.

2020-04-23 22:37 UTC, tariel-x commented on web/web.go
> +	if path != "/" && path[len(path)-1] != '/' {
`strings.HasSuffix`

2020-04-23 22:37 UTC, tariel-x commented on web/web.go
> +	if path != "/" && path[len(path)-1] != '/' {
Какой смысл этого условия, если сюда всегда передаётся `/`?

2020-04-23 22:37 UTC, tariel-x commented on web/web.go
> +func fileServer(r chi.Router, path string, root http.FileSystem) error {
Зачем нужен этот метод?

2020-04-23 22:37 UTC, tariel-x commented on web/web.go
> +	"github.com/polisgo2020/search-Arkronzxc/config"
По какой логике импорты сгруппированы?

2020-04-23 22:37 UTC, tariel-x commented on web/web.go
> +	writer.Header().Set("Content-Type", "application/json")
Если используете chi, почему бы не использовать и https://github.com/go-chi/render .

2020-04-23 22:37 UTC, tariel-x commented on web/web.go
> +	log.Debug().Interface("Final json", finalJson)
Мне кажется, 3 записи лога: `Parse search phrase`, `Resp` и `Final json` можно объединить в одну.

2020-04-23 22:55 UTC, tariel-x commented
Зачем, кстати, CORS в этом проекте? Нужен ли он тут?

2020-04-25 18:25 UTC, Arkronzxc commented on web/web.go
> +func fileServer(r chi.Router, path string, root http.FileSystem) error {
Вынес раздачу статики в отдельный метод

2020-04-25 18:26 UTC, Arkronzxc commented on web/web.go
> +	"github.com/polisgo2020/search-Arkronzxc/config"
Использовал goimports -w .

2020-04-25 18:26 UTC, Arkronzxc commented on web/web.go
> +	log.Debug().Interface("Final json", finalJson)
Переделал

2020-04-25 18:28 UTC, Arkronzxc commented
Как правильно раздать статику в моем случае?
![image](https://user-images.githubusercontent.com/44901274/80287744-b8b65a00-873b-11ea-82a8-2cd6b6acde04.png)

2020-04-25 18:28 UTC, Arkronzxc commented
Без CORS не работает

2020-04-25 18:34 UTC, Arkronzxc commented on config/config.go
> +	var listen, logLevel string
Исправил

2020-04-27 09:00 UTC, tariel-x commented
> Как правильно раздать статику в моем случае?
> ![image](https://user-images.githubusercontent.com/44901274/80287744-b8b65a00-873b-11ea-82a8-2cd6b6acde04.png)

Я выше скидывал пример, где static handler работает. cors, кстати, не нужен, без него работает.

2020-04-27 09:11 UTC, tariel-x commented
Если запускать сервис [на файлах](https://github.com/polisgo2020/main/tree/master/books) с LOGLEVEL=debug , то при запуске сервис выводит какое-то невероятное количество логов, которые к тому же выводятся продолжительное время. Я где-то писал уже комментарии по поводу вывода всего индекса в лог.

2020-05-04 14:17 UTC, merged